package com.kophe.leskladlib.datasource.firestore

internal const val ITEM_TITLE = "title"
internal const val ITEM_BARCODE = "barcode"
internal const val ITEM_ID = "id"
internal const val ITEM_LOCATION_ID = "location_id"
internal const val ITEM_SUBLOCATION_ID = "sublocation_id"
internal const val ITEM_CATEGORY_ID = "category_id"
internal const val ITEM_NOTES = "notes"
internal const val ITEM_SUBCATEGORY_IDS = "subcategory_ids"
internal const val ITEM_DATE_CREATED = "date_created"
internal const val ITEM_DATE_MODIFIED = "date_modified"
internal const val ITEM_HISTORY = "history"
internal const val ITEM_OWNERSHIP_TYPE_ID = "ownership_type_id"
internal const val ITEM_IMAGES = "item_images"
internal const val ITEM_RESPONSIBLE_UNIT_ID =  "responsible_unit_id"
internal const val ITEM_SERIAL_NUMBER = "serial_number"
internal const val ITEM_QUANTITY = "quantity"
internal const val ITEM_SET_OPTIONS  = "set_options"
internal const val ITEM_SET_OPTIONS_PARENT  = "set_options.parent_set_id"
